version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.5.0

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv /tmp/docker/* /usr/bin

      - run: npm install

      - run: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD

      - run: npm run build:image

      - run: npm run build:image:mongo_seed

      - deploy:
          name: Deploy
          command: |
            set -euo pipefail
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker push $DOCKER_REPO:latest
            else
              docker push $DOCKER_REPO:$VER
            fi