version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.5.0

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv /tmp/docker/* /usr/bin

      - run: npm install

      - run:
          name: Login to docker hub
          command: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD

      - run:
          name: Build docker images
          command: |
            set -euo pipefail
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker build -t shaunfowler/sp_server:latest -f Dockerfile .
              docker build -t shaunfowler/sp_mongo_seed:latest -f Dockerfile .
            else
              docker build -t shaunfowler/sp_server:$CIRCLE_SHA1 -f Dockerfile .
              docker build -t shaunfowler/sp_mongo_seed:$CIRCLE_SHA1 -f Dockerfile .
            fi

      - deploy:
          name: Deploy
          command: |
            set -euo pipefail
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker push $DOCKER_REPO:latest
            else
              docker push $DOCKER_REPO:$CIRCLE_SHA1
            fi