version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.5.0

    working_directory: ~/repo

    steps:
      - checkout

      - run: 
          name: Restore npm packages
          command: npm install